name: Deploy Journal API to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 24.199.116.19
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/journal-api
            git pull origin main
            npm ci
            pm2 delete journal-api || true
            pm2 start npm --name journal-api -- run start
